#!/bin/bash

set -e

ENV_NAME=${1:-net}
PYTHON_VERSION=${2:-3.6.1}

# Install pyenv
if ! command -v pyenv; then
    if [[ "$OSTYPE" == "linux-gnu" ]]; then
        sudo yum install -y git gcc make automake openssl-devel libsqlite3x-devel \
             bzip2-devel readline-devel
    fi

    curl -L https://raw.githubusercontent.com/yyuu/pyenv-installer/master/bin/pyenv-installer | bash
fi

# Add pyenv to the shell
export PATH="$HOME/.pyenv/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

# Setup Python
pyenv install $PYTHON_VERSION --skip-existing

# Create virtual environment
if [[ ! -d "$(pyenv root)/versions/$ENV_NAME" ]]; then
    echo "Creating '$ENV_NAME' virtual enviroment"
    pyenv virtualenv $PYTHON_VERSION $ENV_NAME
fi

# Install prerequisites
if [[ "$OSTYPE" == "darwin"* ]]; then
    brew install libdnet graphviz
elif [[ "$OSTYPE" == "linux-gnu" ]]; then
    sudo yum install -y graphviz libdnet tcpdump sqlite
    sudo firewall-cmd --zone=public --add-port=8888/tcp --permanent
fi

# Setup virtual environment
pip install --upgrade pip
pip install --upgrade pip-tools
pip install --upgrade -r requirements.txt

# Currently having issues with pip-compile
pip install --upgrade matplotlib
