#!/bin/bash

ENV_NAME=${1:-net}
PYTHON_VERSION=${2:-3.6.1}

# Setup Python
pyenv install $PYTHON_VERSION --skip-existing

# Create virtual environment
if [[ ! -d "$(pyenv root)/versions/$ENV_NAME" ]]; then
    echo "Creating '$ENV_NAME' virtual enviroment"
    pyenv virtualenv $PYTHON_VERSION $ENV_NAME
fi

# Install prerequisites
brew install libdnet graphviz

# Setup virtual environment
pip install --upgrade pip
pip install --upgrade pip-tools
pip install --upgrade -r requirements.txt

# Currently having issues with pip-compile
pip install --upgrade matplotlib
